-- I2C.vhd

-- Generated using ACDS version 24.1 1077

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity I2C is
	port (
		address       : out std_logic_vector(31 downto 0);                    -- avalon_master.address
		read          : out std_logic;                                        --              .read
		readdata      : in  std_logic_vector(31 downto 0) := (others => '0'); --              .readdata
		readdatavalid : in  std_logic                     := '0';             --              .readdatavalid
		waitrequest   : in  std_logic                     := '0';             --              .waitrequest
		write         : out std_logic;                                        --              .write
		byteenable    : out std_logic_vector(3 downto 0);                     --              .byteenable
		writedata     : out std_logic_vector(31 downto 0);                    --              .writedata
		clk           : in  std_logic                     := '0';             --         clock.clk
		i2c_data_in   : in  std_logic                     := '0';             --   conduit_end.conduit_data_in
		i2c_clk_in    : in  std_logic                     := '0';             --              .conduit_clk_in
		i2c_data_oe   : out std_logic;                                        --              .conduit_data_oe
		i2c_clk_oe    : out std_logic;                                        --              .conduit_clk_oe
		rst_n         : in  std_logic                     := '0'              --         reset.reset_n
	);
end entity I2C;

architecture rtl of I2C is
	component altera_i2cslave_to_avlmm_bridge is
		generic (
			I2C_SLAVE_ADDRESS : std_logic_vector(6 downto 0) := "1010101";
			BYTE_ADDRESSING   : integer                      := 2;
			ADDRESS_STEALING  : integer                      := 0;
			READ_ONLY         : integer                      := 0
		);
		port (
			clk           : in  std_logic                     := 'X';             -- clk
			address       : out std_logic_vector(31 downto 0);                    -- address
			read          : out std_logic;                                        -- read
			readdata      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			readdatavalid : in  std_logic                     := 'X';             -- readdatavalid
			waitrequest   : in  std_logic                     := 'X';             -- waitrequest
			write         : out std_logic;                                        -- write
			byteenable    : out std_logic_vector(3 downto 0);                     -- byteenable
			writedata     : out std_logic_vector(31 downto 0);                    -- writedata
			rst_n         : in  std_logic                     := 'X';             -- reset_n
			i2c_data_in   : in  std_logic                     := 'X';             -- conduit_data_in
			i2c_clk_in    : in  std_logic                     := 'X';             -- conduit_clk_in
			i2c_data_oe   : out std_logic;                                        -- conduit_data_oe
			i2c_clk_oe    : out std_logic                                         -- conduit_clk_oe
		);
	end component altera_i2cslave_to_avlmm_bridge;

begin

	i2cslave_to_avlmm_bridge_0 : component altera_i2cslave_to_avlmm_bridge
		generic map (
			I2C_SLAVE_ADDRESS => "1010101",
			BYTE_ADDRESSING   => 2,
			ADDRESS_STEALING  => 0,
			READ_ONLY         => 0
		)
		port map (
			clk           => clk,           --         clock.clk
			address       => address,       -- avalon_master.address
			read          => read,          --              .read
			readdata      => readdata,      --              .readdata
			readdatavalid => readdatavalid, --              .readdatavalid
			waitrequest   => waitrequest,   --              .waitrequest
			write         => write,         --              .write
			byteenable    => byteenable,    --              .byteenable
			writedata     => writedata,     --              .writedata
			rst_n         => rst_n,         --         reset.reset_n
			i2c_data_in   => i2c_data_in,   --   conduit_end.conduit_data_in
			i2c_clk_in    => i2c_clk_in,    --              .conduit_clk_in
			i2c_data_oe   => i2c_data_oe,   --              .conduit_data_oe
			i2c_clk_oe    => i2c_clk_oe     --              .conduit_clk_oe
		);

end architecture rtl; -- of I2C
